export const ErrorCodes = {
  // Auth
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',

  // Events
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_OWNER: 'EVENT_NOT_OWNER',
  EVENT_INVALID_DATES: 'EVENT_INVALID_DATES',
  EVENT_GALLERY_LIMIT_EXCEEDED: 'EVENT_GALLERY_LIMIT_EXCEEDED',

  // Media
  MEDIA_FILE_REQUIRED: 'MEDIA_FILE_REQUIRED',
  MEDIA_FILES_REQUIRED: 'MEDIA_FILES_REQUIRED',
  MEDIA_FILE_TOO_LARGE: 'MEDIA_FILE_TOO_LARGE',
  MEDIA_INVALID_TYPE: 'MEDIA_INVALID_TYPE',
  MEDIA_SIGNATURE_MISMATCH: 'MEDIA_SIGNATURE_MISMATCH',
  MEDIA_CORRUPT_OR_UNSUPPORTED: 'MEDIA_CORRUPT_OR_UNSUPPORTED',
  MEDIA_STORAGE_NOT_CONFIGURED: 'MEDIA_STORAGE_NOT_CONFIGURED',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_DELETE_FAILED: 'MEDIA_DELETE_FAILED',

  // Tickets
  TICKET_TYPE_NOT_FOUND: 'TICKET_TYPE_NOT_FOUND',
  TICKET_SOLD_OUT: 'TICKET_SOLD_OUT',
  QR_NOT_FOUND: 'QR_NOT_FOUND',
  QR_ALREADY_USED: 'QR_ALREADY_USED',
  QR_CANCELLED: 'QR_CANCELLED',
  BUYER_OR_GUEST_REQUIRED: 'BUYER_OR_GUEST_REQUIRED',

  // Vendors
  VENDOR_PROFILE_EXISTS: 'VENDOR_PROFILE_EXISTS',
  VENDOR_NOT_FOUND: 'VENDOR_NOT_FOUND',
  VENDOR_PROFILE_NOT_FOUND: 'VENDOR_PROFILE_NOT_FOUND',
  VENDOR_REQUEST_DUPLICATE: 'VENDOR_REQUEST_DUPLICATE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  MANUAL_REQUEST_NO_PLATFORM_VENDOR: 'MANUAL_REQUEST_NO_PLATFORM_VENDOR',

  // Generic access
  ACCESS_DENIED: 'ACCESS_DENIED',

  // Venues
  VENUE_PROFILE_EXISTS: 'VENUE_PROFILE_EXISTS',
  VENUE_NOT_FOUND: 'VENUE_NOT_FOUND',
  VENUE_PROFILE_NOT_FOUND: 'VENUE_PROFILE_NOT_FOUND',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',

  // Invitations
  INVITATION_ALREADY_SENT: 'INVITATION_ALREADY_SENT',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',

  // Payments
  STRIPE_NOT_CONFIGURED: 'STRIPE_NOT_CONFIGURED',
  PAID_CHECKOUT_NOT_READY: 'PAID_CHECKOUT_NOT_READY',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',

  // Ticketing — commandes payantes (Vague 5)
  TICKET_ORDER_NOT_FOUND: 'TICKET_ORDER_NOT_FOUND',
  TICKET_ORDER_LINE_DUPLICATE: 'TICKET_ORDER_LINE_DUPLICATE',
  TICKET_ORDER_MIXED_EVENTS: 'TICKET_ORDER_MIXED_EVENTS',
  TICKET_ORDER_PAID_TICKET_REQUIRED: 'TICKET_ORDER_PAID_TICKET_REQUIRED',
  TICKET_ORDER_ADMISSION_NOT_AVAILABLE: 'TICKET_ORDER_ADMISSION_NOT_AVAILABLE',
  TICKET_ORDER_NOT_PENDING: 'TICKET_ORDER_NOT_PENDING',
  TICKET_ORDER_LATE_PAYMENT_REQUIRES_REVIEW: 'TICKET_ORDER_LATE_PAYMENT_REQUIRES_REVIEW',
  TICKET_ORDER_SCENARIO_NOT_ALLOWED: 'TICKET_ORDER_SCENARIO_NOT_ALLOWED',
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  TICKET_ORDER_SETTLEMENT_MISMATCH: 'TICKET_ORDER_SETTLEMENT_MISMATCH',

  // Consistency infrastructure
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD: 'IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD',
  OPERATION_ALREADY_PROCESSING: 'OPERATION_ALREADY_PROCESSING',
  INSUFFICIENT_CAPACITY: 'INSUFFICIENT_CAPACITY',
  REGISTRATION_ALREADY_EXISTS: 'REGISTRATION_ALREADY_EXISTS',

  // Generic
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
