export const ErrorCodes = {
  // Auth
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',

  // Events
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_OWNER: 'EVENT_NOT_OWNER',
  EVENT_INVALID_DATES: 'EVENT_INVALID_DATES',

  // Tickets
  TICKET_TYPE_NOT_FOUND: 'TICKET_TYPE_NOT_FOUND',
  TICKET_SOLD_OUT: 'TICKET_SOLD_OUT',
  QR_NOT_FOUND: 'QR_NOT_FOUND',
  QR_ALREADY_USED: 'QR_ALREADY_USED',
  QR_CANCELLED: 'QR_CANCELLED',
  BUYER_OR_GUEST_REQUIRED: 'BUYER_OR_GUEST_REQUIRED',

  // Vendors
  VENDOR_PROFILE_EXISTS: 'VENDOR_PROFILE_EXISTS',
  VENDOR_NOT_FOUND: 'VENDOR_NOT_FOUND',
  VENDOR_REQUEST_DUPLICATE: 'VENDOR_REQUEST_DUPLICATE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // Venues
  VENUE_PROFILE_EXISTS: 'VENUE_PROFILE_EXISTS',
  VENUE_NOT_FOUND: 'VENUE_NOT_FOUND',

  // Invitations
  INVITATION_ALREADY_SENT: 'INVITATION_ALREADY_SENT',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',

  // Generic
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
